Changes by create-pull-request action
AreWeAntiCheatYet/master-manifest pull request #184
Opened 2024-07-26 02:15 UTC by Starz0r

Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

2024-07-26 03:00 UTC, WhippuSIF requested changes
Remove the link for the status reference. That was also a mistake on my part.

Both this and #183 will resolve [issue #1686](https://github.com/AreWeAntiCheatYet/AreWeAntiCheatYet/issues/1686) once revisions are made.

2024-07-26 03:19 UTC, WhippuSIF commented on manifest-new.json
> +    "reference": "https://www.cbjq.com/show-7126-3-1.html",
Should be left blank

2024-07-30 22:42 UTC, Starz0r commented
Hey, I wanted to thank you for these PRs, even if I'm not able to merge them. So far you are the only other person besides me that knows about the editor!

As you can see, it's still a work-in-progress, but I still try to do my day to day work in it. It still has a few issues, including one it seems you ran into, like being unable to add new anti-cheats. In a way, you have to add it out-of-band first before it shows up, which is an issue I'd like to fix later.

I'm glad you at least attempted these changes at all! Unfortunately, I can't exactly accept these changes as-is at the moment, and this isn't your fault, this is just a duck-taped system I have at the moment to make my life easier. From here, I'll most likely be closing this, and taking the changes and submitting them again so they're mergable. I do plan to allow the editor to be used publicly, and accept submissions from it, but it just isn't there yet. Nonetheless, thank you.

2024-07-30 22:42 UTC, closed without merging

2024-07-30 22:46 UTC, WhippuSIF commented
@Starz0r Thanks. I'll keep that in mind.